const serviceDefinitions = [
  ["Linkvertise", "linkvertise.com", "Ad-link"],
  ["Lootlabs", "lootlabs.gg", "Ad-link"],
  ["Lootlink", "loot-link.com", "Ad-link"],
  ["Lootdest", "lootdest.org", "Ad-link"],
  ["Work.ink", "work.ink", "Ad-link"],
  ["Workink", "workink.net", "Ad-link"],
  ["Rekonise", "rekonise.com", "Social unlock"],
  ["Rekonise org", "rekonise.org", "Social unlock"],
  ["Rkns", "rkns.link", "Social unlock"],
  ["PlatoBoost", "platoboost.com", "Key system"],
  ["Plato Relay", "platorelay.com", "Key system"],
  ["Panda Development", "pandadevelopment.net", "Key system"],
  ["Trigon", "trigonevo.com", "Key system"],
  ["Violated", "violated.lol", "Key system"],
  ["Blox Script", "blox-script.com", "Key system"],
  ["BoBlox Script", "boblox-script.com", "Key system"],
  ["Hydrogen", "hydrogen.lat", "Key system"],
  ["Codex", "codex.lol", "Key system"],
  ["Admaven", "ad-maven.com", "Ad-link"],
  ["Lockr", "lockr.so", "Ad-link"],
  ["Lockr net", "lockr.net", "Ad-link"],
  ["Shortfly", "shrtfly.com", "Ad-link"],
  ["ShrtFly vip", "stfly.vip", "Ad-link"],
  ["SocialWolvez", "socialwolvez.com", "Social unlock"],
  ["LinkUnlocker", "linkunlocker.com", "Ad-link"],
  ["Link-Unlock", "link-unlock.com", "Ad-link"],
  ["AroLinks", "arolinks.com", "Ad-link"],
  ["TP II", "tp.ii", "Ad-link"],
  ["Linkify", "linkify.ru", "Ad-link"],
  ["mBoost", "mboost.me", "Social unlock"],
  ["Social Unlock", "social-unlock.com", "Social unlock"],
  ["Sub2Unlock", "sub2unlock.com", "Social unlock"],
  ["Sub2Unlock me", "sub2unlock.me", "Social unlock"],
  ["Sub2Unlock io", "sub2unlock.io", "Social unlock"],
  ["Sub4Unlock", "sub4unlock.com", "Social unlock"],
  ["Sub4Unlock me", "sub4unlock.me", "Social unlock"],
  ["Boostellar", "bstlar.com", "Ad-link"],
  ["ScriptPasteBins", "scriptpastebins.com", "Paste"],
  ["Bstshrt", "bstshrt.com", "Ad-link"],
  ["SF gl", "sf.gl", "Ad-link"],
  ["YorURL", "yorurl.com", "Ad-link"],
  ["Go YorURL", "go.yorurl.com", "Ad-link"],
  ["Roblox Scripts", "robloxscripts.gg", "Gaming"],
  ["Loanbuzz", "lnbz.la", "Ad-link"],
  ["Linkzy", "linkzy.space", "Ad-link"],
  ["EZ4Short", "ez4short.com", "Ad-link"],
  ["Link4Sub", "link4sub.com", "Social unlock"],
  ["Fly Inc", "rinku.pro", "Ad-link"],
  ["7mib", "7mib.io", "Ad-link"],
  ["Link-Hub", "link-hub.net", "Ad-link"],
  ["Link-To", "link-to.net", "Ad-link"],
  ["Adfoc.us", "adfoc.us", "Ad-link"],
  ["Adf.ly", "adf.ly", "Ad-link"],
  ["Adshrink", "adshrink.it", "Ad-link"],
  ["Adshort", "adshort.co", "Ad-link"],
  ["Adshorti", "adshorti.com", "Ad-link"],
  ["BCVC", "bc.vc", "Ad-link"],
  ["Clk.sh", "clk.sh", "Ad-link"],
  ["Cuty.io", "cuty.io", "Ad-link"],
  ["Exe.io", "exe.io", "Ad-link"],
  ["Exey.io", "exey.io", "Ad-link"],
  ["Exe-link", "exe-link.com", "Ad-link"],
  ["Fc.lc", "fc.lc", "Ad-link"],
  ["Flashx", "flashx.pw", "Ad-link"],
  ["Gplinks", "gplinks.co", "Ad-link"],
  ["Gplinks in", "gplinks.in", "Ad-link"],
  ["Gplinks me", "gplinks.me", "Ad-link"],
  ["Idoc", "idoc.eu", "Ad-link"],
  ["Ouo.io", "ouo.io", "Ad-link"],
  ["Ouo.press", "ouo.press", "Ad-link"],
  ["P. ge", "p.ge", "Ad-link"],
  ["P.lc", "p.lc", "Ad-link"],
  ["Shrinkearn", "shrinkearn.com", "Ad-link"],
  ["Shrinkme", "shrinkme.io", "Ad-link"],
  ["Shrink.pe", "shrink.pe", "Ad-link"],
  ["Shrinkurl", "shrinkurl.org", "Ad-link"],
  ["Shorte.st", "shorte.st", "Ad-link"],
  ["Shortzon", "shortzon.com", "Ad-link"],
  ["Smonet", "smonet.com", "Ad-link"],
  ["Urlcash", "urlcash.net", "Ad-link"],
  ["Urlcut", "urlcut.com", "Ad-link"],
  ["Urlhasbeenblocked", "urlhasbeenblocked.com", "Ad-link"],
  ["Urlpay", "urlpay.in", "Ad-link"],
  ["V2links", "v2links.com", "Ad-link"],
  ["Viplink", "viplink.net", "Ad-link"],
  ["Worldlink", "worldlinkz.com", "Ad-link"],
  ["Z links", "zlinks.io", "Ad-link"],
  ["An1", "an1.com", "Gaming"],
  ["Android Zone", "androidzone.org", "Gaming"],
  ["Datanodes", "datanodes.to", "File host"],
  ["Dropgalaxy", "dropgalaxy.com", "File host"],
  ["Filenext", "filenext.com", "File host"],
  ["Filenium", "filenium.com", "File host"],
  ["Katfile", "katfile.com", "File host"],
  ["MegaUp", "megaup.net", "File host"],
  ["Rapidgator", "rapidgator.net", "File host"],
  ["Rosefile", "rosefile.net", "File host"],
  ["Turbobit", "turbobit.net", "File host"],
  ["Upfiles", "upfiles.com", "File host"],
  ["Uploadgig", "uploadgig.com", "File host"],
  ["Uploaded", "uploaded.net", "File host"],
  ["Uploady", "uploady.io", "File host"],
  ["Uptobox", "uptobox.com", "File host"],
  ["Userscloud", "userscloud.com", "File host"],
  ["1fichier", "1fichier.com", "File host"],
  ["Anonfiles", "anonfiles.com", "File host"],
  ["Bayfiles", "bayfiles.com", "File host"],
  ["Mediafire", "mediafire.com", "File host"],
  ["Pastebin", "pastebin.com", "Paste"],
  ["Paste-Drop", "paste-drop.com", "Paste"],
  ["Pastefy", "pastefy.app", "Paste"],
  ["Paster", "paster.so", "Paste"],
  ["GitHub Gist", "gist.github.com", "Paste"],
  ["Hastebin", "hastebin.com", "Paste"],
  ["PrivateBin", "privatebin.net", "Paste"],
  ["Rentry", "rentry.co", "Paste"],
  ["Codeberg", "codeberg.org", "Paste"],
  ["Twitch", "twitch.tv", "Social"],
  ["Twitter", "twitter.com", "Social"],
  ["X", "x.com", "Social"],
  ["Instagram", "instagram.com", "Social"],
  ["TikTok", "tiktok.com", "Social"],
  ["YouTube", "youtube.com", "Social"],
  ["Facebook", "facebook.com", "Social"],
  ["Reddit", "reddit.com", "Social"],
  ["Discord", "discord.com", "Social"],
  ["Telegram", "t.me", "Social"],
  ["Direct resolver", "*", "Fallback"]
];

const services = serviceDefinitions.map(([name, domain, category]) => ({
  name,
  domain,
  category,
  status: "active"
}));

function detectService(url) {
  const hostname = new URL(url).hostname.toLowerCase();
  return services.find((service) => (
    service.domain !== "*" &&
    (hostname === service.domain || hostname.endsWith(`.${service.domain}`))
  )) || services[services.length - 1];
}

module.exports = { services, detectService };
